Social-main/dwitter/urls.py
from django.urls import path
from .views import dashboard, profile_list,profile

app_name = "dwitter"
urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    ]

Social-main/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("dwitter/", include("dwitter.urls")),
    path("admin/", admin.site.urls),
    path("", include("users.urls"))
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Social-main/users/urls.py
from django import views
from django.urls import include,path
from users.views import register
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views


from .forms import UserPasswordResetForm,UserPasswordChangeForm


urlpatterns = [
    path("", LoginView.as_view()),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", register, name="register"),
    
    path('password_reset/', 
    auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',    
    form_class=UserPasswordResetForm),
    name='password_reset'),

    path('password_change/', 
    auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',    
    form_class=UserPasswordChangeForm),
    name='password_change'),

    ]

Social-main/dwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
        )
    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.set([instance.profile.id])
        user_profile.save()

# Create a Profile for each new user.
#post_save.connect(create_profile, sender=User)
class Dweet(models.Model):
    user = models.ForeignKey(
    User, related_name="dweets", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return (
        f"{self.user} "
        f"({self.created_at:%Y-%m-%d %H:%M}): "
        f"{self.body[:30]}..."
        )

Social-main/users/models.py
from django.db import models

# Create your models here.

Social-main/dwitter/forms.py
# dwitter/forms.py
from django import forms
from .models import Dweet


class DweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
            "placeholder": "Dweet something...",
            "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )
    class Meta:
        model = Dweet
        exclude = ("user", )

Social-main/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordResetForm,PasswordChangeForm
from django.contrib.auth.models import User


class RegiterUserCreationForm(UserCreationForm):
    
    class Meta:
        # fields = UserCreationForm.Meta.fields + ("email",)
        model =User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs) 
        self.fields['username'].widget.attrs.update({ 
            'class': 'input is-success is-rounded', 
            'required':'', 
            'name':'username', 
            'id':'username', 
            'type':'text',     
            }) 
        self.fields['email'].widget.attrs.update({ 
            'class': 'input is-success is-rounded', 
            'required':'', 
            'name':'email', 
            'id':'email', 
            'type':'email',  
            }) 
        self.fields['password1'].widget.attrs.update({ 
            'class': 'input is-success is-rounded', 
            'required':'', 
            'name':'password1', 
            'id':'password1', 
            'type':'password',  
            }) 
        self.fields['password2'].widget.attrs.update({ 
            'class': 'input is-success is-rounded', 
            'required':'', 
            'name':'password2', 
            'id':'password2', 
            'type':'password', 
            }) 



class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget = forms.EmailInput(attrs={"class": "input is-success is-rounded"})

class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordChangeForm, self).__init__(*args, **kwargs)
       
        self.fields["old_password"].widget = forms.PasswordInput(attrs={"class": "input is-success is-rounded"})
        self.fields["new_password1"].widget = forms.PasswordInput(attrs={"class": "input is-success is-rounded"})
        self.fields["new_password2"].widget = forms.PasswordInput(attrs={"class": "input is-success is-rounded"})



        

Social-main/dwitter/views.py
from django.shortcuts import render,redirect
from .forms import DweetForm
from .models import Profile,Dweet 
from django.contrib.auth.decorators import login_required

@login_required
def dashboard(request):
    form = DweetForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect("dwitter:dashboard")

    followed_dweets = Dweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")

    return render(request,"dwitter/dashboard.html",{"form": form, "dweets": followed_dweets},)

@login_required
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles": profiles})

@login_required
def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, "dwitter/profile.html", {"profile": profile})


   

Social-main/users/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from users.forms import RegiterUserCreationForm
from django.contrib import messages

def register(request): 
    form = RegiterUserCreationForm(request.POST or None)
    if  request.method == "POST":        
        if  form.is_valid():
            user = form.save()
            login(request, user)            
            return redirect("dwitter:profile_list")
       
    
    return render(request,"users/register.html",{"form":form})
  

Social-main/dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for dweet in dweets %}
        <div class="box">
            {{dweet.body}} 
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }} by {{ dweet.user.username }})
            </span>
        </div>
    {% endfor %}
</div>

<div class="column is-one-third" id="post_form">

    {% comment %} <div class="block">
        <a href="{% url 'dwitter:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    
    <div class="block">
        <a href="{% url 'dwitter:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div> {% endcomment %}

    <div class="block">
        <div class="block">
            <h2 class="title is-2">Add a Dweet</p>
        </div>
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-success is-fullwidth is-medium mt-5"
                        type="submit">Dweet
                </button>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

Social-main/dwitter/templates/dwitter/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="column">
<div class="block">
<h1 class="title is-1">
{{profile.user.username|upper}}'s Dweets
</h1>
</div>
<form method="post">
    {% csrf_token %}
    <div class="buttons has-addons">
    {% if profile in user.profile.follows.all %}
    <button class="button is-success is-static">Follow</button>
    <button class="button is-danger" name="follow" value="unfollow">
    Unfollow
    </button>
    {% else %}
    <button class="button is-success" name="follow" value="follow">
    Follow
    </button>
    <button class="button is-danger is-static">Unfollow</button>
    {% endif %}
    </div>
    <div class="content">
        {% for dweet in profile.user.dweets.all %}
        <div class="box">
        {{ dweet.body }}
        <span class="is-small has-text-grey-light">
        ({{ dweet.created_at }})
        </span>
        </div>
        {% endfor %}
        </div>
    </form>
</div>

<div class="column is-one-third">
<div class="block">
{% comment %} <a href="{% url 'dwitter:profile_list' %}">
<button class="button is-dark is-outlined is-fullwidth">
All Profiles
</button>
</a> {% endcomment %}
</div>
<div class="block">
<h3 class="title is-4">
{{profile.user.username}} follows:
</h3>
<div class="content">
<ul>
{% for following in profile.follows.all %}
<li>
<a href="{% url 'dwitter:profile' following.id %}">
{{ following }}
</a>
</li>
{% endfor %}
</ul>
</div>
</div>

<div class="block">
    <h3 class="title is-4">
    {{profile.user.username}} is followed by:
    </h3>
    <div class="content">
    <ul>
    {% for follower in profile.followed_by.all %}
    <li>
    <a href="{% url 'dwitter:profile' follower.id %}">
    {{ follower }}
    </a>
    </li>
    {% endfor %}
    </ul>
    </div>
    </div>
    </div>

   
    {% endblock content %}

Social-main/dwitter/templates/dwitter/profile_list.html
<!-- dwitter/templates/dwitter/profile_list.html -->
{% extends 'base.html' %}
{% block content %}
  <div class="column">
    {% for profile in profiles %}
      <div class="block">
        <div class="card">
          <a href="{% url 'dwitter:profile' profile.id %}">
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image" />
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4">{{ profile.user.username }}</p>
                  <p class="subtitle is-6">@{{ profile.user.username|lower }}</p>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

Social-main/templates/base.html
<!-- dwitter/templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <title>Dwitter</title>
  </head>
  <body >
    <section class="hero is-small is-success mb-4">
    <nav class="navbar is-success " role="navigation" aria-label="main navigation" >
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'dwitter:dashboard' %}">
          <img src="{% static "img/dwitter.png" %}" width="112" height="28">
        </a>
    
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
     
      <div id="navbarBasicExample" class="navbar-menu">
       
        <div class="navbar-start">
           {% if request.user.is_authenticated %}
          <a class="navbar-item"  href="{% url 'dwitter:profile' request.user.profile.id %}">
            My Profile
          </a>
          <a class="navbar-item"  href="{% url 'dwitter:profile_list' %}">
            All Profiles
          </a>
          <a class="navbar-item" href="{% url 'password_change' %}">
            Change Password
          </a>
    
        </div>
    
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              
              <div class="is-pulled-right ">
                 <a class="button is-family-secondary" href="{% url 'logout' %}">
                   <strong>Logout</strong>
                   </a>
               </div>   
               {%else%}
                        
            
              {% comment %} <a class="button is-family-secondary" href="{% url 'login' %}">
              <strong>Login</strong>
              </a>
              <a class="button is-family-secondary" href="{% url 'register' %}">
              <strong>Sign up</strong>
              </a>  {% endcomment %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
	
  </section>


    {% comment %} <section class="hero is-small is-success mb-4">
      <div class="hero-body"  >
        <h1 class="title is-1">Dwitter</h1>
        <p class="subtitle is-4">Your tiny social network built with Django</p>
       
      </div>
     
         {% if request.user.is_authenticated %}
         <div class="is-pulled-right ">
            <a href="{% url 'logout' %}" class="subtitle is-5">Logout</a>
            <a class="button is-primary" href="{% url 'logout' %}">
              <strong>Logout</strong>
              </a>
          </div>            
        {% endif %}
          
      
    </section> {% endcomment %}
    <div class="container">
      <div class="columns">
        {% block content %}

        {% endblock %}
      </div>
    </div>
  </body>
</html>

Social-main/users/templates/users/register.html
<!--users/templates/users/register.html-->
 {% extends 'base.html' %}
{% block content %}
<style>
    ul {
      list-style-type: circle;
      font-size: 12px;
      margin-left: 25px;
    }
    ul.errorlist{
        list-style-type:none;
        font-size: 15px;
        color:red;
    }
    .helptext{
        font-size: 13px;
    }
    p{
        margin-top:10px;
    }
    label{
        color: #363636;
        display: block;
        font-size: 1rem;
        font-weight: 700;
    }
</style>    
    
<div class="column is-one-quarter"></div>
<div class="column is-half">
    
    <form method="post">
        {% csrf_token %}
        <div class="is-fullheight">
            <div class="hero-body is-justify-content-center is-align-items-center " >
                <div class="columns is-flex is-flex-direction-column box ">
                    <h2 class="title is-success has-text-centered">Register</h2>
                    {{form.as_p}}
                    <div class="column">
                        <button class="button is-success is-fullwidth is-rounded" type="submit">Register</button>
                    </div>
                    <div class="has-text-centered">
                        <p class="is-size-7"> Already have an account?  
                            <a href="{% url 'login' %}" class="has-text-success">Login</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}  